[package]
name = "PaintDroid"
version = "0.1.0"
authors = ["Auteur <Courriel@nom.domaine.tld"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
